name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: useblacksmith/setup-zig@v3
        with:
          version: 0.14.0

      - name: Build
        run: zig build

      - name: Run Tests
        run: zig build test
